export const SET_JOINED_SERVERS = "SET_JOINED_SERVERS"
export const SET_ACTIVE_SERVER = "SET_ACTIVE_SERVER"
export const SET_ACTIVE_CHANNEL = "SET_ACTIVE_CHANNEL"
export const UPDATE_JOINED_SERVERS = "UPDATE_JOINED_SERVERS"